apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: demo-app
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: demo-app
  type: LoadBalancer
