apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: todo-mysql-data
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: demo-app-configmap
                  key: database_name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
      restartPolicy: Always
      volumes:
        - name: todo-mysql-data
          persistentVolumeClaim:
            claimName: todo-mysql-data
