apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-username: cm9vdA== # this is taken by running echo -n root | base64
    mysql-password: c2VjcmV0 # this is taken by running echo -n secret | base64

